apiVersion: v2
name: k8s-playground-0.1.3
description: A Helm chart for k8s Playground application
type: application
version: 0.1.3
appVersion: "v0.1.3"
keywords:
  - kubernetes
  - playground
  - dind
  - development
home: https://github.com/tyottodekiru/k8s-playground
sources:
  - https://github.com/tyottodekiru/k8s-playground
maintainers:
  - name: k8s-playground
    email: gtpgx305@gmail.com
