apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-playground.fullname" . }}-logging-controller-headless
  labels:
    {{- include "k8s-playground.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging-controller
spec:
  clusterIP: None
  selector:
    {{- include "k8s-playground.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: logging-controller
  ports:
  - name: admin-api
    port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-playground.fullname" . }}-logging-controller
  labels:
    {{- include "k8s-playground.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging-controller
spec:
  type: ClusterIP
  selector:
    {{- include "k8s-playground.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: logging-controller
  ports:
  - name: admin-api
    port: 8081
    targetPort: 8081