apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-playground.fullname" . }}
  labels:
    {{- include "k8s-playground.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: ["apps"]
  # Added deployments resource for workload management
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-playground.fullname" . }}
  labels:
    {{- include "k8s-playground.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-playground.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-playground.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
