{{- if .Values.deployment.security.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-playground.serviceAccountName" . }}
  labels:
    {{- include "k8s-playground.labels" . | nindent 4 }}
  {{- with .Values.deployment.security.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
