apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-playground.fullname" . }}-logging-admin
  labels:
    {{- include "k8s-playground.labels" . | nindent 4 }}
    app.kubernetes.io/component: logging-admin
type: Opaque
data:
  # Generate a random token for logging admin access
  # This will be used by app-controller to access logging-controller's internal API
  token: {{ include "k8s-playground.loggingAdminToken" . | b64enc | quote }}
---
{{- define "k8s-playground.loggingAdminToken" -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-logging-admin" (include "k8s-playground.fullname" .))) -}}
{{- if $secret -}}
{{/* If secret already exists, reuse the token */}}
{{- index $secret.data "token" | b64dec | trimSuffix "\n" -}}
{{- else -}}
{{/* Generate new token */}}
{{- randAlphaNum 32 -}}
{{- end -}}
{{- end -}}